export default {
  UPDATE_NEW_TODO: 'UPDATE_NEW_TODO',
  DONE_TODO: 'DONE_TODO',
  UPDATE_TODO_FILTER: 'UPDATE_TODO_FILTER',
  ADD_NEW_WEIGHT: 'ADD_NEW_WEIGHT',
  UPDATE_WEIGHT_RECORDS: 'UPDATE_WEIGHT_RECORDS',
  ADD_NEW_TODO: 'ADD_NEW_TODO'
}
