const WEIGHT_MUTATION_TYPES = {
  ADD_NEW_WEIGHT: 'ADD_NEW_WEIGHT',
  UPDATE_WEIGHT_RECORDS: 'UPDATE_WEIGHT_RECORDS'
}

const RUBIK_CUBE_MUTATION_TYPES = {
  SPEED_3_RECORD_SAVED: 'SPEED_3_RECORD_SAVED',
  SPEED_3_RECORDS_RECEIVED: 'SPEED_3_RECORDS_RECEIVED'
}

const COMMON_MUTATION_TYPES = {
  UPDATE_TITLE: 'UPDATE_TITLE'
}

export default {
  ...COMMON_MUTATION_TYPES,
  ...WEIGHT_MUTATION_TYPES,
  ...RUBIK_CUBE_MUTATION_TYPES
}
